### ISSUE TITLE
Flow errors

### ISSUE THREAD

**Issue by Li0liQ** [faceyspacey/redux-first-router-link#62] opened 2017-10-03 05:46 UTC
I am getting a number of [flow validation errors](https://gist.github.com/Li0liQ/0463a6d10ab73343b6f360705706e769) when running `redux-first-router-link` and having `redux-first-router` [flow-typed](https://github.com/faceyspacey/redux-first-router/pull/131).
Please, fix and release `redux-first-router-link` before next version of `redux-first-router` is released or it will break consumers' flow validation.

**Comment by craigambrose** [comment] 2017-11-13 05:24
I can confirm that I'm getting errors with this too.

```
Error: node_modules/redux-first-router-link/dist/handlePress.js.flow:7
  7: export type OnClick = false | ((SyntheticEvent) => ?boolean)
                                     ^^^^^^^^^^^^^^ SyntheticEvent. Application of polymorphic type needs <list of 0-1 arguments>. (Can use `*` for inferrable ones)

Error: node_modules/redux-first-router-link/dist/handlePress.js.flow:17
 17:   e: SyntheticEvent
          ^^^^^^^^^^^^^^ SyntheticEvent. Application of polymorphic type needs <list of 0-1 arguments>. (Can use `*` for inferrable ones)

Error: node_modules/redux-first-router-link/dist/preventDefault.js.flow:3
  3: export default (e: SyntheticEvent) =>
                        ^^^^^^^^^^^^^^ SyntheticEvent. Application of polymorphic type needs <list of 0-1 arguments>. (Can use `*` for inferrable ones)
```

It looks like react dom / flow expects to have Synthetic event templated on the input type, such as SyntheticEvent<HTMLFormElement>.

**Comment by faceyspacey** [comment] 2017-11-13 12:38
This will be addressed in the next version.

**Closed** 2017-11-28 20:57 UTC
